### ISSUE TITLE
Update to latest libs

### ISSUE THREAD

**Issue by menion** [asamm/locus-addon-wearables#7]
Before further development, it is necessary to update to latest libs used by this project.

The best should be to check current Wear OS requirements.

What definitely needs to be done:

- [x] update to Locus API 0.9.39
- [x] update to AndroidX
- [ ] update TargetSdk to 30

**Comment by menion** [comment]
Update to Locus API done in [commit to dev/update](https://github.com/asamm/locus-addon-wearables/commit/a2bfa2647e0ef33197775279ee696bb1a3343b2e) branch.

**Comment by wansti** [comment]
Am I correct that this doesn't compile yet? Or did I do something wrong?

I'm interested to see what TargetSdk 30 will do to the WearableDrawerView, with Samsung's quick settings panel in WearOS 3.0 effectively breaking the drawer pulled in from the top.

**Comment by menion** [comment]
Hi Marek, I've tested the "wear" module yesterday and it worked on the emulator correctly. 

You probably miss parameters for signing necessary in the Gradle script.

I've updated the old Locus API wiki ... so [here](https://github.com/asamm/locus-api/wiki/Adding-Locus-API-to-project#signing) are steps to set this up. Let me know if it helps.

**Comment by wansti** [comment]
Hi Menion, I came across a few classes that still referenced old library components such as "ActionTools". Will double-check that I set it up correctly. Thanks!

**Comment by wansti** [comment]
Update - the errors are in the "device" module (DeviceCommService and PeriodicUpdateReceiver). The "wear" module compiles fine and runs on the emulator. However I cannot connect it to the main app anymore (which worked before). 
![Screenshot](https://user-images.githubusercontent.com/1392063/133215277-af08f406-aa7c-4a1c-a989-212b93d53b00.png)

**Comment by menion** [comment]
Thank you Marek! I'll check it more carefully, hopefully, today, and let you know here.

I believe that updating the whole project to the latest versions is necessary before continuing in any development.

**Comment by menion** [comment]
Uff, the app now compile and start. But seems there is a new different problem. Created device APK does not contain necessary `DeviceCommService` and `DeviceListenerService` objects. Hmm ...

**Comment by wansti** [comment]
Interesting, I'm getting a different error and a crash from "device":

```E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.asamm.locus.addon.wear, PID: 29813
    java.lang.RuntimeException: Unable to instantiate application com.asamm.locus.addon.wear.MainApplication: java.lang.ClassNotFoundException: Didn't find class "com.asamm.locus.addon.wear.MainApplication" on path: DexPathList[[zip file "/data/app/~~HVQSrOHb89theKV4LHbELA==/com.asamm.locus.addon.wear-2SbCvNZnYJ4TwJVaj2eQZw==/base.apk"],nativeLibraryDirectories=[/data/app/~~HVQSrOHb89theKV4LHbELA==/com.asamm.locus.addon.wear-2SbCvNZnYJ4TwJVaj2eQZw==/lib/x86, /system/lib, /system_ext/lib]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1244)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6683)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.asamm.locus.addon.wear.MainApplication" on path: DexPathList[[zip file "/data/app/~~HVQSrOHb89theKV4LHbELA==/com.asamm.locus.addon.wear-2SbCvNZnYJ4TwJVaj2eQZw==/base.apk"],nativeLibraryDirectories=[/data/app/~~HVQSrOHb89theKV4LHbELA==/com.asamm.locus.addon.wear-2SbCvNZnYJ4TwJVaj2eQZw==/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1158)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1236)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6683) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
W/System: A resource failed to call close. ```

**Comment by menion** [comment]
You are fast. Hmm, I've just before commit also change `MainApplication` from Java to Kotlin and now you have this error. This is a clue, thanks :).

**Comment by wansti** [comment]
Haha I was just looking through the code when your commit came in. Locus Map is literally the reason I own a smartwatch so this is exciting. :)

**Comment by menion** [comment]
So, both modules are now working and communication between them should be finally working as well. Uff ...

Seems that dirty work should be done. So if you are still interested, it is time to play ;).

I currently do not have time for active work on this add-on, but I'll be available as much as possible for possible questions or PR reviews. Thanks for your interest btw!

**Comment by wansti** [comment]
Yup, got it working in the emulator! I'll have a play with it and see how far I get.

No worries, thanks for putting in that extra work, and thanks for a great app!
